// Sprite variables
let startBar,
    title,
    id,
    person,
    ball,
    ballShape,
    personShape,
    leftAnimateTextures,
    rightAnimateTextures,
    gameBackground,
    circleList = [],
    circleNumList = [],
    numStyle,
    blackCircleTexture,
    whiteCircleTexture,
    jumpHighLimited,
    ballSAT,
    personSAT,
    personPath,
    personPathSAT = [],
    collided,
    circle,
    response,
    nextBtn,
    banner,
    bigBoard,
    tutorialBackground,
    startBtn,
    coverBoard,
    resultBox,
    restartText,
    resultText,
    totalScoreText,
    scoreText,
    tutorialText;
